language: node_js
cache: yarn
node_js:
  - "10"
deploy:
  on:
    tags: true
  provider: npm
  email: itamarjr91@gmail.com
  api_key:
    secure: U5bi7pjqSfHI58on2LUXMoX2HOfVlCLLq2EG2FvBl7TUsieAicAcaKgl2/lMbhCkTGxA87vjf8AQnPes8EpKgrpRzGXnhWcPwMLSCk6GEOgJ9kcdcKIZky/jUGpWSiCVvMaFoACcJASn+ANDZ4YkCNXPql0GxU8QluKNPkjKjEpfxILMfl3qAi5RcHxjhw3uN6O4IldJWqDGsBRHYUept0rtCi9UZO9FnVDXDdCzacxMQ+GTq6kSTUR0oz8P7f5Eb9hYv98yWmevfjmYl02mKyIZ1Y0+KXCEj6dOTpTOkFbGOrN6p6wcT2Q8iOoGYbIOz1xfFfjXJm6tQJOFJF8TUNVLxa2uZSdtX33GjL4FjIGyKJnEXgThExJ5WGQ+ebshuoybTxoE1tUMYmu8YK+0QNHImUUvrYlfUJvzwAPUdz7rRuPV11daJfmJlDI6+iAoWI1oqUjeyNV3lcOSEWQmCfEe9zB/RalURXFTdnexl6OsdilqFqPys3Ha6GBWqVpljtnv7NSypwaf9rGPOnm80s3AUSqoLT8I71b57Hd0fhzS4hdJjO8E4UzcN1guNrTHYoCAg45b8tlFIfGwcMAIRSwL4GU1aS/bBQJqMxVAQ4dBqxQ+la4doYRfIiOJqpo0fkQGnKhTflI6a8If7RAucxNdDqpFnZ0ougcVhlXfZMs=
