language: node_js
cache: yarn
node_js:
  - "10"
before_deploy: "echo 'Deploying to NPM...'"
deploy:
  on:
    tags: true
  provider: npm
  email: itamarjr91@gmail.com
  api_key:
    secure: luyajnh9r+V7Z6HCShFK3VL5H7mfDF65URXmSvAGik8kUbYoSdIWzBbeTP9wrM6G7+3SHDeopk+uFYLv6/cMov6XVSpeVJup3xJFAbcHAmtayK/o9E2Ph6EOioxkSljTpzlzcAfMFA0wEx3lE3DgQUkbEVUQrnIwn1WVKkeD7klCaGxeVmUfwRwRvJaaVuU09Qevvg/oq7rJIBkPYZCfMDKaYQY4MTnIcEZn9G1NSngTfhxXp9lW678p70WCdle6EPvC8d9gJFS1BB8ozeS0sj6hhJIuTVc1ObPMGrsLXzp44RaXVD6xP4dka4gyPAsBRhskUJT3qvmHdAvYlRXGtIsLliRafMlEiycPC/6e7NiBaWKVaOXQu0sgWHSLJf+hNg+VIQd8HMrt3sfOXkZIwwtT7S7zEmIr90UnRJZYiGRR9Xs2tMPkjkzr9O9rW0t7PURaFQJMq/LLFNIHJuQnfUZN8mKFBsn52W34PY/3eQoDB6xg9ilb2uvKsFvTlEjze14gdYLxfyxe5BXzFGWUG73CuhgKwJix1enjSLLai/9bXL8JTioR83zZLiFb9vx2kUUUnXj9fHsnLX5HL1IfR9hXXME6nH7bgUSQ7IBeI41JHS8Vrcc8kRXn/+7W5JTU2XcWnmQtgZmi/WkOm99gB7BgmNxxlOBHaM2PuUkOtKs=
after_deploy: "Package deployed to NPM!"
